### ISSUE TITLE
2.0 Kunden verwalten

### ISSUE THREAD

**Issue by easys1lex** [easys1lex/projectvibe#32]
Die Lösung enthält Kunden.
Folgende Funktionen können genutzt werden:
- [ ] [2.1 Kunden anlegen](../issues/26)
- [ ] [2.2 Kunden löschen](../issues/27)
- [ ] [2.3 Kundendaten ändern](../issues/28)
- [ ] [2.4 Kunden sortieren](../issues/29)
- [ ] [2.5 Kunden suchen](../issues/30)
- [ ] [2.6 Zwischen business und Privatkunden unterscheiden](../issues/31)

- [ ] Alle Methoden sind mit Unit Spezifikationen beschreiben.
- [ ] Alerts werden genutzt.
